language: generic
sudo: required

services:
  - docker
before_install:
  - docker build -t pankaj/reactimage:latest Dockerfile.dev .
script:
  - docker run -e CI=true pankaj/reactimage:latest npm run test
