sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pankaj/reactimage:latest -f Dockerfile.dev .

script:
  - docker run -e CI=true pankaj/reactimage:latest npm run test
